---

dontChroot: false
timeout: 999
script:
    - "-rm -r @@ROOT@@/etc/calamares/"
    - "mkdir -p /etc/systemd/system/multi-user.target.wants"
    - "ln -sf /etc/systemd/system/shopno-os-first-boot.service /etc/systemd/system/multi-user.target.wants/shopno-os-first-boot.service"
